stages:
    correlate:
        cmd: python3 src/correlate.py
        deps:
        - src/correlate.py
        - src/getaroundr.py
        - input/cv01.fits
        - input/cv02.fits
        - input/cv11.fits
        - input/cv12.fits
        params:
        - common.log_path
        - correlate.radius
        - correlate.cat
        - correlate.iRA
        - correlate.iDEC
        - correlate.asfx
        outs:
        - data/j_cv01.fits
        - data/j_cv02.fits
        - data/j_cv11.fits
        - data/j_cv12.fits
    merge:
        cmd: python3 src/merge.py
        deps:
        - src/merge.py
        - data/j_cv01.fits
        - data/j_cv02.fits
        - data/j_cv11.fits
        - data/j_cv12.fits
        - input/cv0.csv
        - input/cv1.csv
        - input/sdss.gz_pkl
        outs:
        - data/cv01.csv
        - data/cv02.csv
        - data/cv11.csv
        - data/cv12.csv
        - data/1cv01.csv
        - data/1cv02.csv
        - data/1cv11.csv
        - data/1cv12.csv
    featurize:
        cmd: python3 src/featurize.py input/features.pkl data/df_featurize.csv
        params:
        - featurize.column
        - featurize.mode
        - featurize.overview
        deps:
        - src/featurize.py
        - input/features.pkl
        - data/1cv01.csv
        - data/1cv02.csv
        - data/1cv11.csv
        - data/1cv12.csv
        outs:
        - data/df_featurize.csv
    train:
        cmd: python3 src/train.py data/df_featurize.csv data/df_train.pkl data/df_test.pkl models/model.pkl models/robust.pkl
        params:
        - common.log_path
        deps:
        - src/train.py
        - src/train_lib.py
        - data/df_featurize.csv
        outs:
        - data/df_train.pkl
        - data/df_test.pkl
        - models/model.pkl
        - models/robust.pkl
    validate:
        cmd: python3 src/validate.py models/model.pkl models/robust.pkl data/df_test.pkl scores.json
        deps:
        - src/validate.py
        - models/model.pkl
        - models/robust.pkl
        - data/df_test.pkl
        metrics:
        - scores.json:
              cache: false
