common:
    log_path: logs/

correlate:
    radius: 3.0
    cat: uhs1v1
    iRA: ra
    iDEC: dec
    asfx: _

featurize:
    column: JAPERMAG3
    mode: j
    overview: sdssdr16+psdr2+wise_decals8tr
