name: dvc_astro
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GOOGLE_DRIVE_STORAGE }}
        run: |
          pip install -r requirements.txt
          dvc pull
          echo "dvc pull completed sucessfully" > report.md
          dvc repro >> report.md
          echo "dvc repro completed sucessfully" >> report.md
          dvc metrics show -A >> report.md
          cml-send-comment report.md

